### ISSUE TITLE
App crash by OOM when sending ctrl+c to interrupt

### ISSUE THREAD

**Issue by noel2004** [scroll-tech/go-ethereum#180]
#### System information

Geth version: `pre-alpha 2.2`
OS & Version: Windows
Commit hash :

#### Expected behaviour

When syncing up with network (~377k blocks), use ctrl-c to interrupt the app, it should close normally.

Then the node can restart from the block number it has stopped at.

#### Actual behaviour

It print following logs, and crash because of OOM. The app eat up almost all memory in a machine with 128G RAM and crash:

> INFO [11-14|15:29:20.917] Writing cached state to disk             block=377,131 hash=903b13..685bb8 root=2e4bdb..f7111f
> INFO [11-14|15:29:27.862] Deep froze chain segment                 blocks=18    elapsed=27.846ms  number=287,131 hash=00e50f..1ab9d3
> INFO [11-14|15:29:55.932] Looking for peers                        peercount=0 tried=1 static=1
> runtime: VirtualAlloc of 260866048 bytes failed with errno=1455
> fatal error: out of memory

After relaunching the app, all blocks data has been lost and it has to re-syncing from beginning:

> INFO [11-14|15:30:38.693] Loaded most recent local full block      number=377,131 hash=903b13..685bb8 td=379,349 age=1m20s
> INFO [11-14|15:30:38.693] Loaded most recent local fast block      number=377,131 hash=903b13..685bb8 td=379,349 age=1m20s
> WARN [11-14|15:30:38.694] Head state missing, repairing            number=377,131 hash=903b13..685bb8
> INFO [11-14|15:33:27.083] Loaded most recent local header          number=1       hash=3e157e..310799 td=3       age=1mo3w22h
> INFO [11-14|15:33:27.083] Loaded most recent local full block      number=1       hash=3e157e..310799 td=3       age=1mo3w22h
> INFO [11-14|15:33:27.083] Loaded most recent local fast block      number=1       hash=3e157e..310799 td=3       age=1mo3w22h
> INFO [11-14|15:33:27.084] Gasprice oracle is ignoring threshold set threshold=2
> WARN [11-14|15:33:27.085] Unclean shutdown detected                booted=2022-11-14T14:30:13+0800 age=1h3m14s

#### Steps to reproduce the behaviour

Following the instruction in [running your own l2geth node](https://www.notion.so/scrollzkp/Docs-Running-your-own-l2geth-node-c5b63bdb631d44298e2d659bf26becca), then wait for syncing finishing, and stop app. Then relaunch it.

#### Backtrace

````
runtime stack:
runtime.throw({0x7ff772469f12?, 0xd5ecbb1000?})
        runtime/panic.go:992 +0x76
runtime.sysUsed(0xd5e7e32000, 0xf8c8000)
        runtime/mem_windows.go:83 +0x1c9
runtime.(*mheap).allocSpan(0x7ff7730f53c0, 0x7c64, 0x0, 0x1)
        runtime/mheap.go:1279 +0x428
runtime.(*mheap).alloc.func1()
        runtime/mheap.go:912 +0x65
runtime.systemstack()
        runtime/asm_amd64.s:469 +0x4e

goroutine 386887 [running]:
runtime.systemstack_switch()
        runtime/asm_amd64.s:436 fp=0xc000555750 sp=0xc000555748 pc=0x7ff771119c00
runtime.(*mheap).alloc(0x291b4bdb560?, 0xc0005557d8?, 0x5?)
        runtime/mheap.go:906 +0x65 fp=0xc000555798 sp=0xc000555750 pc=0x7ff7710d8a65
runtime.(*mcache).allocLarge(0xc0145afba0?, 0xf8c6054, 0x1)
        runtime/mcache.go:213 +0x85 fp=0xc0005557e8 sp=0xc000555798 pc=0x7ff7710c8c65
runtime.mallocgc(0xf8c6054, 0x7ff772224440, 0x1)
        runtime/malloc.go:1096 +0x5a5 fp=0xc000555860 sp=0xc0005557e8 pc=0x7ff7710bef05
runtime.makeslice(0xc00078bb20?, 0xd1cd536000?, 0xc000555918?)
        runtime/slice.go:103 +0x52 fp=0xc000555888 sp=0xc000555860 pc=0x7ff7710ff752
github.com/syndtr/goleveldb/leveldb.(*Batch).grow(...)
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/batch.go:82
github.com/syndtr/goleveldb/leveldb.(*Batch).appendRec(0xc4c2232dc0, 0x1, {0xc3a7006c00?, 0x20?, 0x7ff772308f80?}, {0xc21f5f64e0, 0x41, 0xc9e9aff900?})
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/batch.go:93 +0xf7 fp=0xc000555950 sp=0xc000555888 pc=0x7ff7713c8377
github.com/syndtr/goleveldb/leveldb.(*Batch).Put(...)
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/batch.go:118
github.com/scroll-tech/go-ethereum/ethdb/leveldb.(*batch).Put(0xc01c016408, {0xc3a7006c00?, 0x20, 0x40?}, {0xc21f5f64e0?, 0x41, 0x60?})
        github.com/scroll-tech/go-ethereum/ethdb/leveldb/leveldb.go:458 +0x50 fp=0xc0005559a0 sp=0xc000555950 pc=0x7ff77142ebb0
github.com/scroll-tech/go-ethereum/trie.(*Database).Commit(0xc0005d5180, {0x2e, 0x4b, 0xdb, 0xb0, 0xd9, 0x2a, 0x17, 0x7f, 0x25, ...}, ...)
        github.com/scroll-tech/go-ethereum/trie/database.go:713 +0x183 fp=0xc000555bd0 sp=0xc0005559a0 pc=0x7ff77147ee63
github.com/scroll-tech/go-ethereum/core.(*BlockChain).Stop(0xc0002db080?)
        github.com/scroll-tech/go-ethereum/core/blockchain.go:824 +0x765 fp=0xc000555e68 sp=0xc000555bd0 pc=0x7ff77166a985
github.com/scroll-tech/go-ethereum/eth.(*Ethereum).Stop(0xc0002bc870)
        github.com/scroll-tech/go-ethereum/eth/backend.go:559 +0xb3 fp=0xc000555e98 sp=0xc000555e68 pc=0x7ff7718a0f93
github.com/scroll-tech/go-ethereum/node.(*Node).stopServices(0xc000254c30, {0xc000905560, 0x1, 0x0?})
        github.com/scroll-tech/go-ethereum/node/node.go:296 +0xbe fp=0xc000555f10 sp=0xc000555e98 pc=0x7ff771818fbe
github.com/scroll-tech/go-ethereum/node.(*Node).Close(0xc000254c30)
        github.com/scroll-tech/go-ethereum/node/node.go:216 +0x191 fp=0xc000555fc8 sp=0xc000555f10 pc=0x7ff7718186b1
github.com/scroll-tech/go-ethereum/cmd/utils.StartNode.func1.3()
        github.com/scroll-tech/go-ethereum/cmd/utils/cmd.go:93 +0x26 fp=0xc000555fe0 sp=0xc000555fc8 pc=0x7ff771b22286
runtime.goexit()
        runtime/asm_amd64.s:1571 +0x1 fp=0xc000555fe8 sp=0xc000555fe0 pc=0x7ff77111bf81
created by github.com/scroll-tech/go-ethereum/cmd/utils.StartNode.func1
        github.com/scroll-tech/go-ethereum/cmd/utils/cmd.go:93 +0x310

goroutine 1 [chan receive, 59 minutes]:
github.com/scroll-tech/go-ethereum/node.(*Node).Wait(...)
        github.com/scroll-tech/go-ethereum/node/node.go:423
main.geth(0xc0000f6dc0)
        github.com/scroll-tech/go-ethereum/cmd/geth/main.go:323 +0x10a
gopkg.in/urfave/cli%2ev1.HandleAction({0x7ff7722337c0?, 0x7ff7726c9c18?}, 0xc0000db000?)
        gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0x5a
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc000498b60, {0xc0000dc000, 0x11, 0x20})
        gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x71c
main.main()
        github.com/scroll-tech/go-ethereum/cmd/geth/main.go:262 +0x35

goroutine 7 [chan receive, 1 minutes]:
github.com/scroll-tech/go-ethereum/core.(*txSenderCacher).cache(0xc000533fb8?)
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:63 +0x3b
created by github.com/scroll-tech/go-ethereum/core.newTxSenderCacher
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:55 +0x75

goroutine 8 [chan receive, 1 minutes]:
github.com/scroll-tech/go-ethereum/core.(*txSenderCacher).cache(0x0?)
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:63 +0x3b
created by github.com/scroll-tech/go-ethereum/core.newTxSenderCacher
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:55 +0x75

goroutine 9 [chan receive, 1 minutes]:
github.com/scroll-tech/go-ethereum/core.(*txSenderCacher).cache(0xc00032ffb8?)
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:63 +0x3b
created by github.com/scroll-tech/go-ethereum/core.newTxSenderCacher
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:55 +0x75

goroutine 10 [chan receive, 1 minutes]:
github.com/scroll-tech/go-ethereum/core.(*txSenderCacher).cache(0x0?)
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:63 +0x3b
created by github.com/scroll-tech/go-ethereum/core.newTxSenderCacher
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:55 +0x75

goroutine 11 [chan receive, 3 minutes]:
github.com/scroll-tech/go-ethereum/core.(*txSenderCacher).cache(0x3f?)
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:63 +0x3b
created by github.com/scroll-tech/go-ethereum/core.newTxSenderCacher
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:55 +0x75

goroutine 12 [chan receive, 1 minutes]:
github.com/scroll-tech/go-ethereum/core.(*txSenderCacher).cache(0x697b10896487efb?)
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:63 +0x3b
created by github.com/scroll-tech/go-ethereum/core.newTxSenderCacher
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:55 +0x75

goroutine 13 [chan receive, 1 minutes]:
github.com/scroll-tech/go-ethereum/core.(*txSenderCacher).cache(0x10925878a22951d2?)
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:63 +0x3b
created by github.com/scroll-tech/go-ethereum/core.newTxSenderCacher
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:55 +0x75

goroutine 14 [chan receive, 3 minutes]:
github.com/scroll-tech/go-ethereum/core.(*txSenderCacher).cache(0x12bc2f8ea309d0aa?)
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:63 +0x3b
created by github.com/scroll-tech/go-ethereum/core.newTxSenderCacher
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:55 +0x75

goroutine 15 [chan receive, 3 minutes]:
github.com/scroll-tech/go-ethereum/core.(*txSenderCacher).cache(0xb27d402fc69e2f2?)
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:63 +0x3b
created by github.com/scroll-tech/go-ethereum/core.newTxSenderCacher
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:55 +0x75

goroutine 16 [chan receive, 1 minutes]:
github.com/scroll-tech/go-ethereum/core.(*txSenderCacher).cache(0x40?)
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:63 +0x3b
created by github.com/scroll-tech/go-ethereum/core.newTxSenderCacher
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:55 +0x75

goroutine 50 [chan receive, 3 minutes]:
github.com/scroll-tech/go-ethereum/core.(*txSenderCacher).cache(0x11a6eaf2aa551837?)
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:63 +0x3b
created by github.com/scroll-tech/go-ethereum/core.newTxSenderCacher
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:55 +0x75

goroutine 51 [chan receive, 3 minutes]:
github.com/scroll-tech/go-ethereum/core.(*txSenderCacher).cache(0x40?)
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:63 +0x3b
created by github.com/scroll-tech/go-ethereum/core.newTxSenderCacher
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:55 +0x75

goroutine 52 [chan receive, 3 minutes]:
github.com/scroll-tech/go-ethereum/core.(*txSenderCacher).cache(0x1b3af1fa25c32da1?)
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:63 +0x3b
created by github.com/scroll-tech/go-ethereum/core.newTxSenderCacher
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:55 +0x75

goroutine 53 [chan receive, 1 minutes]:
github.com/scroll-tech/go-ethereum/core.(*txSenderCacher).cache(0xc00059a030?)
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:63 +0x3b
created by github.com/scroll-tech/go-ethereum/core.newTxSenderCacher
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:55 +0x75

goroutine 54 [chan receive, 3 minutes]:
github.com/scroll-tech/go-ethereum/core.(*txSenderCacher).cache(0x2af5dfa19ccc918d?)
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:63 +0x3b
created by github.com/scroll-tech/go-ethereum/core.newTxSenderCacher
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:55 +0x75

goroutine 55 [chan receive, 3 minutes]:
github.com/scroll-tech/go-ethereum/core.(*txSenderCacher).cache(0xc000596810?)
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:63 +0x3b
created by github.com/scroll-tech/go-ethereum/core.newTxSenderCacher
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:55 +0x75

goroutine 56 [chan receive, 1 minutes]:
github.com/scroll-tech/go-ethereum/core.(*txSenderCacher).cache(0x27f16feaf6fe1525?)
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:63 +0x3b
created by github.com/scroll-tech/go-ethereum/core.newTxSenderCacher
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:55 +0x75

goroutine 57 [chan receive, 1 minutes]:
github.com/scroll-tech/go-ethereum/core.(*txSenderCacher).cache(0xc0005ac090?)
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:63 +0x3b
created by github.com/scroll-tech/go-ethereum/core.newTxSenderCacher
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:55 +0x75

goroutine 58 [chan receive, 3 minutes]:
github.com/scroll-tech/go-ethereum/core.(*txSenderCacher).cache(0x1324564ac7bdf9e2?)
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:63 +0x3b
created by github.com/scroll-tech/go-ethereum/core.newTxSenderCacher
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:55 +0x75

goroutine 59 [chan receive, 1 minutes]:
github.com/scroll-tech/go-ethereum/core.(*txSenderCacher).cache(0xc0005a8870?)
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:63 +0x3b
created by github.com/scroll-tech/go-ethereum/core.newTxSenderCacher
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:55 +0x75

goroutine 60 [chan receive, 1 minutes]:
github.com/scroll-tech/go-ethereum/core.(*txSenderCacher).cache(0x437b94aeaefff8e?)
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:63 +0x3b
created by github.com/scroll-tech/go-ethereum/core.newTxSenderCacher
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:55 +0x75

goroutine 61 [chan receive, 3 minutes]:
github.com/scroll-tech/go-ethereum/core.(*txSenderCacher).cache(0xc0005b70b0?)
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:63 +0x3b
created by github.com/scroll-tech/go-ethereum/core.newTxSenderCacher
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:55 +0x75

goroutine 62 [chan receive, 3 minutes]:
github.com/scroll-tech/go-ethereum/core.(*txSenderCacher).cache(0x0?)
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:63 +0x3b
created by github.com/scroll-tech/go-ethereum/core.newTxSenderCacher
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:55 +0x75

goroutine 63 [chan receive, 1 minutes]:
github.com/scroll-tech/go-ethereum/core.(*txSenderCacher).cache(0xc0005ad890?)
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:63 +0x3b
created by github.com/scroll-tech/go-ethereum/core.newTxSenderCacher
        github.com/scroll-tech/go-ethereum/core/tx_cacher.go:55 +0x75

goroutine 64 [chan receive]:
github.com/scroll-tech/go-ethereum/metrics.(*meterArbiter).tick(0x7ff7730cd920)
        github.com/scroll-tech/go-ethereum/metrics/meter.go:290 +0x65
created by github.com/scroll-tech/go-ethereum/metrics.NewMeterForced
        github.com/scroll-tech/go-ethereum/metrics/meter.go:71 +0xc5

goroutine 65 [select]:
github.com/scroll-tech/go-ethereum/consensus/ethash.(*remoteSealer).loop(0xc0005dc4b0)
        github.com/scroll-tech/go-ethereum/consensus/ethash/sealer.go:279 +0x205
created by github.com/scroll-tech/go-ethereum/consensus/ethash.startRemoteSealer
        github.com/scroll-tech/go-ethereum/consensus/ethash/sealer.go:263 +0x319

goroutine 70 [select, 17 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc0003888c0)
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_compaction.go:91 +0x158
created by github.com/syndtr/goleveldb/leveldb.openDB
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:148 +0x4ea

goroutine 99 [select, 59 minutes]:
github.com/scroll-tech/go-ethereum/accounts.(*Manager).update(0xc0005d50a0)
        github.com/scroll-tech/go-ethereum/accounts/manager.go:134 +0x14d
created by github.com/scroll-tech/go-ethereum/accounts.NewManager
        github.com/scroll-tech/go-ethereum/accounts/manager.go:94 +0x2b5

goroutine 100 [select]:
github.com/scroll-tech/go-ethereum/accounts/keystore.(*KeyStore).updater(0xc0005dcff0)
        github.com/scroll-tech/go-ethereum/accounts/keystore/keystore.go:209 +0x85
created by github.com/scroll-tech/go-ethereum/accounts/keystore.(*KeyStore).Subscribe
        github.com/scroll-tech/go-ethereum/accounts/keystore/keystore.go:196 +0x110

goroutine 101 [select, 3 minutes]:
github.com/syndtr/goleveldb/leveldb.(*session).refLoop(0xc0005dd0e0)
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/session_util.go:189 +0x59b
created by github.com/syndtr/goleveldb/leveldb.newSession
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/session.go:93 +0x2d9

goroutine 71 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc0003888c0)
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_state.go:101 +0xa8
created by github.com/syndtr/goleveldb/leveldb.openDB
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:149 +0x52a

goroutine 72 [select, 17 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc0003888c0)
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_compaction.go:836 +0x657
created by github.com/syndtr/goleveldb/leveldb.openDB
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:155 +0x598

goroutine 73 [select, 17 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc0003888c0)
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_compaction.go:773 +0x113
created by github.com/syndtr/goleveldb/leveldb.openDB
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:156 +0x5d6

goroutine 74 [select]:
github.com/scroll-tech/go-ethereum/ethdb/leveldb.(*Database).meter(0xc0002a8100, 0x9982e3bb81e38b82?)
        github.com/scroll-tech/go-ethereum/ethdb/leveldb/leveldb.go:433 +0x178a
created by github.com/scroll-tech/go-ethereum/ethdb/leveldb.NewCustom
        github.com/scroll-tech/go-ethereum/ethdb/leveldb/leveldb.go:149 +0x825

goroutine 75 [select, 1 minutes]:
github.com/scroll-tech/go-ethereum/core/rawdb.(*freezer).freeze(0xc0005f2200, {0x7ff77286e988?, 0xc0002a8100})
        github.com/scroll-tech/go-ethereum/core/rawdb/freezer.go:355 +0x19e
github.com/scroll-tech/go-ethereum/core/rawdb.NewDatabaseWithFreezer.func1()
        github.com/scroll-tech/go-ethereum/core/rawdb/database.go:222 +0x2a
created by github.com/scroll-tech/go-ethereum/core/rawdb.NewDatabaseWithFreezer
        github.com/scroll-tech/go-ethereum/core/rawdb/database.go:221 +0x870

goroutine 121 [chan receive, 1 minutes]:
github.com/scroll-tech/go-ethereum/eth/gasprice.NewOracle.func1()
        github.com/scroll-tech/go-ethereum/eth/gasprice/gasprice.go:123 +0x8d
created by github.com/scroll-tech/go-ethereum/eth/gasprice.NewOracle
        github.com/scroll-tech/go-ethereum/eth/gasprice/gasprice.go:121 +0x96d

goroutine 122 [select, 15 minutes]:
github.com/scroll-tech/go-ethereum/eth/downloader.(*PublicDownloaderAPI).eventLoop(0xc000241a00)
        github.com/scroll-tech/go-ethereum/eth/downloader/api.go:63 +0x1f3
created by github.com/scroll-tech/go-ethereum/eth/downloader.NewPublicDownloaderAPI
        github.com/scroll-tech/go-ethereum/eth/downloader/api.go:49 +0x105

goroutine 124 [chan receive, 5 minutes]:
github.com/scroll-tech/go-ethereum/eth/filters.(*PublicFilterAPI).timeoutLoop(0xc0000a1cc0, 0x0?)
        github.com/scroll-tech/go-ethereum/eth/filters/api.go:82 +0x9b
created by github.com/scroll-tech/go-ethereum/eth/filters.NewPublicFilterAPI
        github.com/scroll-tech/go-ethereum/eth/filters/api.go:70 +0x149

goroutine 125 [select, 5 minutes]:
github.com/syndtr/goleveldb/leveldb.(*session).refLoop(0xc000120f00)
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/session_util.go:189 +0x59b
created by github.com/syndtr/goleveldb/leveldb.newSession
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/session.go:93 +0x2d9

goroutine 130 [select, 59 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc000185dc0)
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_compaction.go:91 +0x158
created by github.com/syndtr/goleveldb/leveldb.openDB
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:148 +0x4ea

goroutine 131 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc000185dc0)
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_state.go:101 +0xa8
created by github.com/syndtr/goleveldb/leveldb.openDB
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:149 +0x52a

goroutine 132 [select, 59 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc000185dc0)
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_compaction.go:836 +0x657
created by github.com/syndtr/goleveldb/leveldb.openDB
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:155 +0x598

goroutine 133 [select, 59 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc000185dc0)
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_compaction.go:773 +0x113
created by github.com/syndtr/goleveldb/leveldb.openDB
        github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:156 +0x5d6

goroutine 135 [select, 11 minutes]:
github.com/scroll-tech/go-ethereum/p2p/nat.Map({0x7ff772869ec0?, 0xc000790380}, 0xc0002db980, {0x7ff77245e783, 0x3}, 0x765f, 0x765f, {0x7ff772468ab9, 0xc})
        github.com/scroll-tech/go-ethereum/p2p/nat/nat.go:114 +0x3f8
github.com/scroll-tech/go-ethereum/p2p.(*Server).setupListening.func1()
        github.com/scroll-tech/go-ethereum/p2p/server.go:673 +0x5e
created by github.com/scroll-tech/go-ethereum/p2p.(*Server).setupListening
        github.com/scroll-tech/go-ethereum/p2p/server.go:672 +0x1b2

goroutine 136 [IO wait, 59 minutes]:
internal/poll.runtime_pollWait(0x290f8811b18, 0x72)
        runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0x290f5f501a0?, 0xd0?, 0x0)
        internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.execIO(0xc0003aac98, 0xc00086bc88)
        internal/poll/fd_windows.go:175 +0xe5
internal/poll.(*FD).acceptOne(0xc0003aac80, 0x430, {0xc0002c2690?, 0x3?, 0xc0005f8820?}, 0xc000228ba0?)
        internal/poll/fd_windows.go:942 +0x6d
internal/poll.(*FD).Accept(0xc0003aac80, 0xc00086be60)
        internal/poll/fd_windows.go:976 +0x1d6
net.(*netFD).accept(0xc0003aac80)
        net/fd_windows.go:139 +0x65
net.(*TCPListener).accept(0xc0005c27f8)
        net/tcpsock_posix.go:139 +0x28
net.(*TCPListener).Accept(0xc0005c27f8)
        net/tcpsock.go:288 +0x3d
github.com/scroll-tech/go-ethereum/p2p.(*Server).listenLoop(0xc000269180)
        github.com/scroll-tech/go-ethereum/p2p/server.go:862 +0x627
created by github.com/scroll-tech/go-ethereum/p2p.(*Server).setupListening
        github.com/scroll-tech/go-ethereum/p2p/server.go:680 +0x20a

goroutine 139 [chan receive, 59 minutes]:
github.com/scroll-tech/go-ethereum/p2p/enode.(*FairMix).nextFromAny(...)
        github.com/scroll-tech/go-ethereum/p2p/enode/iter.go:241
github.com/scroll-tech/go-ethereum/p2p/enode.(*FairMix).Next(0xc0005e3020)
        github.com/scroll-tech/go-ethereum/p2p/enode/iter.go:215 +0x2c5
github.com/scroll-tech/go-ethereum/p2p.(*dialScheduler).readNodes(0xc000410000, {0x7ff772867dd0, 0xc0005e3020})
        github.com/scroll-tech/go-ethereum/p2p/dial.go:322 +0x9f
created by github.com/scroll-tech/go-ethereum/p2p.newDialScheduler
        github.com/scroll-tech/go-ethereum/p2p/dial.go:180 +0x425

goroutine 140 [select]:
github.com/scroll-tech/go-ethereum/p2p.(*dialScheduler).loop(0xc000410000, {0x7ff772867dd0, 0xc0005e3020})
        github.com/scroll-tech/go-ethereum/p2p/dial.go:243 +0x2ba
created by github.com/scroll-tech/go-ethereum/p2p.newDialScheduler
        github.com/scroll-tech/go-ethereum/p2p/dial.go:181 +0x49e

goroutine 141 [select]:
github.com/scroll-tech/go-ethereum/p2p.(*Server).run(0xc000269180)
        github.com/scroll-tech/go-ethereum/p2p/server.go:714 +0x4cc
created by github.com/scroll-tech/go-ethereum/p2p.(*Server).Start
        github.com/scroll-tech/go-ethereum/p2p/server.go:487 +0x46a

goroutine 165 [chan receive, 1 minutes]:
github.com/scroll-tech/go-ethereum/cmd/utils.StartNode.func1()
        github.com/scroll-tech/go-ethereum/cmd/utils/cmd.go:95 +0x33a
created by github.com/scroll-tech/go-ethereum/cmd/utils.StartNode
        github.com/scroll-tech/go-ethereum/cmd/utils/cmd.go:76 +0xb9

goroutine 102 [syscall, 1 minutes]:
os/signal.signal_recv()
        runtime/sigqueue.go:151 +0x2f
os/signal.loop()
        os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
        os/signal/signal.go:151 +0x2a

goroutine 103 [sleep, 1 minutes]:
time.Sleep(0xdf8475800)
        runtime/time.go:194 +0x133
github.com/scroll-tech/go-ethereum/cmd/utils.monitorFreeDiskSpace(0x0?, {0xc0003ca000, 0x32}, 0x10000000)
        github.com/scroll-tech/go-ethereum/cmd/utils/cmd.go:119 +0x57
created by github.com/scroll-tech/go-ethereum/cmd/utils.StartNode.func1
        github.com/scroll-tech/go-ethereum/cmd/utils/cmd.go:88 +0x29b

goroutine 167 [select, 1 minutes]:
github.com/scroll-tech/go-ethereum/rpc.(*Client).dispatch(0xc00053e000, {0x7ff77286b1f0?, 0xc00053a0f0})
        github.com/scroll-tech/go-ethereum/rpc/client.go:576 +0x2cc
created by github.com/scroll-tech/go-ethereum/rpc.initClient
        github.com/scroll-tech/go-ethereum/rpc/client.go:240 +0x3aa

goroutine 168 [chan receive, 59 minutes]:
main.startNode.func1()
        github.com/scroll-tech/go-ethereum/cmd/geth/main.go:358 +0x89
created by main.startNode
        github.com/scroll-tech/go-ethereum/cmd/geth/main.go:350 +0x18a
````

When submitting logs: please submit them as text and not screenshots.

**Comment by lispc** [comment]
add `--gcmode=archive`  and retry?

**Comment by noel2004** [comment]
> add `--gcmode=archive` and retry?

Would try this option after [this issue](https://github.com/scroll-tech/go-ethereum/issues/177) has been resolved

**Comment by noel2004** [comment]
`--gcmode=archive` resolve the issue and following is the reason:

zktrie add an `rawDirties` in trie database layer, directly put any updating into this entry, and expect the flush of db persisting these dirty writings.

It works well if node flush database peroidly (after every block), which is just how miner or archive mode works.

However, `gcmode=full` do not persist dirty data into database but kept them in memory. Only the "top" state trie would be written when app is stopped. For zktrie, a simple kvmap for dirty means they would be all kept and written on exit, there is no way to gc the expired state nodes like the origin trie do.
