### ISSUE TITLE
Uniswap v3 test partial failed on zkrollup branch

### ISSUE THREAD

**Issue by lightsing** [scroll-tech/go-ethereum#50]
### Reproduce

testing on commit f8532484a6887641b29a88fc8b0b7df06d4cf51b
with https://github.com/Uniswap/v3-core

#### v3-core modificiation
```
+++ b/hardhat.config.ts
@@ -4,7 +4,13 @@ import '@nomiclabs/hardhat-waffle'
 import '@nomiclabs/hardhat-etherscan'

 export default {
+  defaultNetwork: "localhost",
   networks: {
+    localhost: {
+      url: "http://127.0.0.1:8545",
+      gas: 0x6691b7,
+      gasPrice: 1e9,
+    },
     hardhat: {
       allowUnlimitedContractSize: false,
     },
```

after start geth node, run `npx hardhat test --network localhost`

### Part failed test

```
  10) Tick
       #getFeeGrowthInside
         subtracts upper tick if below:
     AssertionError: Expected "15" to be equal 13
      at Context.<anonymous> (test\Tick.spec.ts:70:54)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  11) Tick
       #getFeeGrowthInside
         subtracts lower tick if above:
     AssertionError: Expected "15" to be equal 13
      at Context.<anonymous> (test\Tick.spec.ts:85:54)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  12) Tick
       #getFeeGrowthInside
         subtracts upper and lower tick if inside:
     AssertionError: Expected "15" to be equal 9
      at Context.<anonymous> (test\Tick.spec.ts:110:54)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  13) Tick
       #getFeeGrowthInside
         works correctly with overflow on inside tick:
     AssertionError: Expected "15" to be equal 16
      at Context.<anonymous> (test\Tick.spec.ts:135:54)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  14) Tick
       #update
         does not flip from nonzero to greater nonzero:

      AssertionError: expected true to equal false
      + expected - actual

      -true
      +false

      at Context.<anonymous> (test\Tick.spec.ts:145:100)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

```
  18) Tick
       #update
         reverts if total liquidity gross is greater than max:

      AssertionError: Expected transaction to be reverted
      + expected - actual

      -Transaction NOT reverted.
      +Transaction reverted.



  19) Tick
       #update
         nets the liquidity based on upper flag:
     AssertionError: Expected "0" to be equal 7
      at Context.<anonymous> (test\Tick.spec.ts:170:48)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  20) Tick
       #update
         reverts on overflow liquidity gross:

      AssertionError: Expected transaction to be reverted
      + expected - actual

      -Transaction NOT reverted.
      +Transaction reverted.



  21) Tick
       #update
         assumes all growth happens below ticks lte current tick:
     AssertionError: Expected "0" to be equal 1
      at Context.<anonymous> (test\Tick.spec.ts:180:55)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  22) Tick
       #update
         does not set any growth fields if tick is already initialized:
     AssertionError: Expected "0" to be equal 1
      at Context.<anonymous> (test\Tick.spec.ts:191:55)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  23) Tick
       #update
         does not set any growth fields for ticks gt current tick:

      AssertionError: expected false to equal true
      + expected - actual

      -false
      +true

      at Context.<anonymous> (test\Tick.spec.ts:206:45)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  24) Tick
       #cross
         flips the growth variables:
     AssertionError: Expected "0" to be equal 6
      at Context.<anonymous> (test\Tick.spec.ts:248:55)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  25) Tick
       #cross
         two flips are no op:
     AssertionError: Expected "0" to be equal 1
      at Context.<anonymous> (test\Tick.spec.ts:268:55)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  26) TickBitmap
       #isInitialized
         is flipped by #flipTick:

      AssertionError: expected false to equal true
      + expected - actual

      -false
      +true

      at Context.<anonymous> (test\TickBitmap.spec.ts:26:67)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  27) TickBitmap
       #isInitialized
         is not changed by another flip to a different tick on another word:

      AssertionError: expected false to equal true
      + expected - actual

      -false
      +true

      at Context.<anonymous> (test\TickBitmap.spec.ts:39:69)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  28) TickBitmap
       #flipTick
         flips only the specified tick:

      AssertionError: expected false to equal true
      + expected - actual

      -false
      +true

      at Context.<anonymous> (test\TickBitmap.spec.ts:46:70)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  29) TickBitmap
       #flipTick
         reverts only itself:

      AssertionError: expected false to equal true
      + expected - actual

      -false
      +true

      at Context.<anonymous> (test\TickBitmap.spec.ts:66:70)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by lightsing** [comment]
UPDATE: this issue exists on the original geth.
